/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 src/assets/models/squirtle2.gltf -o src/components/Squirtle2.jsx -r src 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Squirtle2(props) {
  const { nodes, materials } = useGLTF("/models/squirtle2.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          geometry={nodes.Squirtle_body_body.geometry}
          material={materials.lambert1}
        />
        <mesh
          geometry={nodes.Squirtle_body_foot_L.geometry}
          material={materials.lambert1}
        />
        <mesh
          geometry={nodes.Squirtle_body_foot_R.geometry}
          material={materials.lambert1}
        />
        <mesh
          geometry={nodes.Squirtle_body_hand_L.geometry}
          material={materials.lambert1}
        />
        <mesh
          geometry={nodes.Squirtle_body_hand_R.geometry}
          material={materials.lambert1}
        />
        <mesh
          geometry={nodes.Squirtle_body_tail.geometry}
          material={materials.lambert1}
        />
        <mesh
          geometry={nodes.Squirtle_head_face.geometry}
          material={materials.lambert1}
        />
        <mesh
          geometry={nodes.Squirtle_head_tongue.geometry}
          material={materials.lambert1}
        />
        <mesh
          geometry={nodes.Squirtle_head_eyes_L_ball.geometry}
          material={materials.lambert1}
        />
        <mesh
          geometry={nodes.Squirtle_head_eyes_R_ball.geometry}
          material={materials.lambert1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/squirtle2.gltf");
